### PR TITLE
Bring Dockerfile current with "activegraph" naming

### PR DESCRIPTION
**Pull request by RyanSnodgrass**
Bring the Dockerfile up to date with the current structure of the gem.

1. Update gemfile directory paths
2. Follow github actions test and install bundler to latest 2.x version

```
$ docker build -t activegraph-gem .
```

### CODE REVIEW

**Comment by klobuczek** [comment]
`seabolt` has been discontinued. The PR in this form should be raised against branch 10 and possibly a different one against master.

**Comment by RyanSnodgrass** [comment]
@klobuczek What bolt adapter would you recommend?

**Comment by RyanSnodgrass** [comment]
> The PR in this form should be raised against branch 10 

done - https://github.com/neo4jrb/activegraph/pull/1659

**Comment by klobuczek** [comment]
If you stiil would like this PR merge to master remove the seabolt references and use jruby.

**Comment by RyanSnodgrass** [comment]
I can do that, but why? Will the master branch always be jruby?

**Comment by RyanSnodgrass** [comment]
>  remove the seabolt references and use jruby.

Done.

**Review by klobuczek — APPROVED** [review]

**Pull request merged**
