### PR TITLE
Zeitwerk migration + activesupport 7.1 support

### PR DESCRIPTION
**Pull request by klobuczek**

### CODE REVIEW

**Comment by dgertych-monterail** [comment]
This is what I am waiting for :) Will it be released in the near future?

**Comment by klobuczek** [comment]
@chytreg sorry, we are trying to release the branch this week

**Comment by klobuczek** [comment]
@chytreg please have a look at [11.5.0.beta.1](https://rubygems.org/gems/activegraph/versions/11.5.0.beta.1) and let us know if you find any issues.

**Comment by klobuczek** [comment]
PR already merged branch 11

**Pull request closed without merging**
